// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGpPntWjwF30z063mFYfNxcB7LgOvIT9g',
    appId: '1:1048160192798:web:538e0242f888ed24f2a10f',
    messagingSenderId: '1048160192798',
    projectId: 'promo-club-46acd',
    authDomain: 'promo-club-46acd.firebaseapp.com',
    storageBucket: 'promo-club-46acd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMj4Qf2hTq1NsdLaJ1IOBIDVHeLTlGgG4',
    appId: '1:1048160192798:android:b240b99fdf049bd7f2a10f',
    messagingSenderId: '1048160192798',
    projectId: 'promo-club-46acd',
    storageBucket: 'promo-club-46acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPJL_9PydVgj1DFnyPT1-qjYojqU3VuYI',
    appId: '1:1048160192798:ios:f5ab042ee1ab1a94f2a10f',
    messagingSenderId: '1048160192798',
    projectId: 'promo-club-46acd',
    storageBucket: 'promo-club-46acd.appspot.com',
    iosBundleId: 'com.example.promoClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPJL_9PydVgj1DFnyPT1-qjYojqU3VuYI',
    appId: '1:1048160192798:ios:f5ab042ee1ab1a94f2a10f',
    messagingSenderId: '1048160192798',
    projectId: 'promo-club-46acd',
    storageBucket: 'promo-club-46acd.appspot.com',
    iosBundleId: 'com.example.promoClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGpPntWjwF30z063mFYfNxcB7LgOvIT9g',
    appId: '1:1048160192798:web:18205f5f893d6f35f2a10f',
    messagingSenderId: '1048160192798',
    projectId: 'promo-club-46acd',
    authDomain: 'promo-club-46acd.firebaseapp.com',
    storageBucket: 'promo-club-46acd.appspot.com',
  );
}
